print("hellow oworld across the internet")
print("the messgae above was written on my pc, this is a new message i wrote on my laptop")
print ("This is my sister")
print(" 2nd fork")
print ("3rd fork or maybe a branch... idk this is stange ")
print ("....")
print ("this is my fork")
